services:
  db:
    image: mysql:latest
    container_name: greenacesso-database
    # restart: always
    ports:
      - "9000:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=greenacesso
      - MYSQL_DATABASE=greenacesso
      - MYSQL_USER=greenacesso
      - MYSQL_PASSWORD=greenacesso_pass
